### ISSUE TITLE
[EPIC] HTTP Errors classes

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/Siemply#6]
# [EPIC] HTTP Errors

According to: 

https://github.com/Siemienik/Siemply/blob/563f0cbfad481690f7d9558f87df49e8499b30a2/src/errors.ts#L34

Blocked by: #4 

In some cases like object not found the handler should throws http errors.

## Current

The main handler catches http errors, then builds the response base on the catched error. Until now there is only defined 2 http errors:

* HttpBadRequestError:

https://github.com/Siemienik/Siemply/blob/563f0cbfad481690f7d9558f87df49e8499b30a2/src/errors.ts#L14-L22

* HttpNotFoundError

https://github.com/Siemienik/Siemply/blob/563f0cbfad481690f7d9558f87df49e8499b30a2/src/errors.ts#L23-L32

## Expected

It will covers the most popular of 4xx and 5xx error responses: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

* Organizational tickets:
    * [ ] Create ticket per error
    * [ ] Extract erros from errors.ts to errors/NAME.ts
* 4xx Client Error
    * [x] 400 Bad Request
    * [ ] 401 Unauthorized
    * [ ] 403 Forbidden
    * [x] 404 Not Found
    * [ ] 405 Method Not Allowed
    * [ ] 406 Not Acceptable
    * [ ] 407 Proxy Authentication Required
    * [ ] 408 Request Timeout
    * [ ] 409 Conflict
    * [ ] 410 Gone
    * [ ] 411 Length Required
    * [ ] 412 Precondition Failed
    * [ ] 413 Request Entity Too Large
    * [ ] 414 Request-URI Too Long
    * [ ] 415 Unsupported Media Type
    * [ ] 416 Requested Range Not Satisfiable
    * [ ] 417 Expectation Failed
    * [ ] 418 I'm a teapot (RFC 2324)
    * [ ] 426 Upgrade Required
    * [ ] 428 Precondition Required
    * [ ] 429 Too Many Requests
    * [ ] 431 Request Header Fields Too Large
    * [ ] 451 Unavailable For Legal Reasons
 
* 5xx Server Error
    * [ ] 500 Internal Server Error
    * [ ] 501 Not Implemented
    * [ ] 502 Bad Gateway
    * [ ] 503 Service Unavailable
    * [ ] 504 Gateway Timeout
    * [ ] 505 HTTP Version Not Supported
    * [ ] 510 Not Extended
    * [ ] 511 Network Authentication Required
    * [ ] 598 Network read timeout error
    * [ ] 599 Network connect timeout error
